vich_uploader:
    db_driver: orm

    mappings:
        profile:
            uri_prefix: /upload/profile
            upload_destination: '%kernel.project_dir%/public/upload/profile'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_remove: false
            delete_on_update: false

        coffee:
            uri_prefix: /upload/coffee
            upload_destination: '%kernel.project_dir%/public/upload/coffee'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_remove: false
            delete_on_update: false

